Update the pnp system to support separate input and output channels for each app triplet. Update all tests to conform.
Modify configure to support ORCM_DESTDIR directives. Update make_tarball so it immediately warns you and aborts if --with-orte is not provided (eliminate bonehead errors).



git-svn-id: http://svn.open-mpi.org/svn/orcm/trunk@75 e75c48be-c379-0410-a98d-d1e110c868e2

diff --git a/contrib/dist/make_dist_tarball b/contrib/dist/make_dist_tarball
--- a/contrib/dist/make_dist_tarball
+++ b/contrib/dist/make_dist_tarball
@@ -63,6 +63,11 @@ while test "${var}" != ""; do
     var=$1
 done
 
+if [ "${withorte}" = " " ]; then
+    echo "Must supply --with-orte=<path-to-orte-installation> - Aborting"
+    exit 1
+fi
+
 #
 # First things first -- check that the auto versions that we have are
 # the ones that we want.
